# Generated by Django 3.2.12 on 2023-11-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='cpassword',
        ),
    ]
