# Generated by Django 3.2.12 on 2023-11-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_registeruser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='uname',
        ),
    ]
